"""Database models and connection for the weather trading bot."""
import logging
from datetime import datetime
from typing import Optional
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, Boolean, JSON, text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from sqlalchemy import inspect
import enum

from backend.config import settings

logger = logging.getLogger("trading_bot")

engine = create_engine(
    settings.DATABASE_URL,
    connect_args={"check_same_thread": False} if "sqlite" in settings.DATABASE_URL else {}
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


class Trade(Base):
    """Simulated trades for tracking P&L."""
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, index=True)
    signal_id = Column(Integer, index=True)
    market_ticker = Column(String, index=True)
    platform = Column(String)
    event_slug = Column(String, nullable=True)
    market_type = Column(String, default="btc", index=True)  # "btc" or "weather"
    bucket_label = Column(String, nullable=True)  # exact range bet, e.g. "88-89°F" (weather)

    # Trade details
    direction = Column(String)  # "up" or "down"
    entry_price = Column(Float)
    size = Column(Float)
    timestamp = Column(DateTime, default=datetime.utcnow)

    # Settlement
    settled = Column(Boolean, default=False)
    settlement_time = Column(DateTime, nullable=True)
    settlement_value = Column(Float, nullable=True)  # 1.0=Up won, 0.0=Down won
    result = Column(String, default="pending")  # pending, win, loss
    pnl = Column(Float, nullable=True)           # net of fees
    fee = Column(Float, default=0.0)             # trading fee paid at entry (Phase 6)

    # Model performance tracking
    model_probability = Column(Float)
    market_price_at_entry = Column(Float)
    edge_at_entry = Column(Float)

    # Scoreboard cohort: was a per-station forecast bias applied to this trade's
    # city+metric at entry? True = corrected city (NYC/Chicago/Miami/Denver/
    # London/Paris), False = uncorrected (LA/Tokyo/Seoul/HK/Shanghai), NULL =
    # unknown/legacy. Set at trade time so it stays honest if a city is later fixed.
    bias_corrected = Column(Boolean, nullable=True)


class BotState(Base):
    """Bot state and statistics."""
    __tablename__ = "bot_state"

    id = Column(Integer, primary_key=True)
    bankroll = Column(Float, default=10000.0)
    total_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    total_pnl = Column(Float, default=0.0)
    last_run = Column(DateTime, nullable=True)
    is_running = Column(Boolean, default=False)


class Signal(Base):
    """Trading signals generated by the bot."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, index=True)
    market_ticker = Column(String, index=True)
    platform = Column(String)
    market_type = Column(String, default="btc", index=True)  # "btc" or "weather"
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)

    direction = Column(String)
    model_probability = Column(Float)
    market_price = Column(Float)
    edge = Column(Float)
    confidence = Column(Float)

    # Cost-aware economics (Phase 6 + Layer 1) — recorded so the scoreboard can
    # prove an edge NET of costs, and so the dashboard can show why a bucket was
    # or wasn't traded. Nullable: legacy/BTC signals won't have them.
    net_edge = Column(Float, nullable=True)      # gross edge minus spread/2 + fee
    entry_price = Column(Float, nullable=True)   # effective price we'd pay (real ask)
    cost = Column(Float, nullable=True)          # per-share cost (spread/2 + fee)
    rel_spread = Column(Float, nullable=True)    # spread as a fraction of side price
    liquidity = Column(Float, nullable=True)     # $ resting in the book at scan time

    kelly_fraction = Column(Float)
    suggested_size = Column(Float)

    sources = Column(JSON)
    reasoning = Column(String)

    executed = Column(Boolean, default=False)

    # Calibration tracking — filled after settlement
    actual_outcome = Column(String, nullable=True)    # actual result in the signal's vocab ("yes"/"no" weather, "up"/"down" legacy)
    outcome_correct = Column(Boolean, nullable=True)   # did our direction prediction match?
    settlement_value = Column(Float, nullable=True)     # 1.0=UP won, 0.0=DOWN won
    settled_at = Column(DateTime, nullable=True)        # when we recorded the outcome


class WorkingOrder(Base):
    """A resting LIMIT order placed by the MAKER path (backend/core/maker.py), persisted so it
    survives across poll cycles and restarts. A working order is NOT yet a position — it becomes
    a ``Trade`` only when (and for the amount) it actually fills. Unfilled orders expire (GTD) and
    leave no Trade. This keeps the Trade table's meaning intact (a Trade = a filled position).

    The simulator's resting state (queue_ahead, last_poll_ts, filled so far) lives here so each
    poll reconstructs the order, advances it against the real trade tape, and writes it back.
    """
    __tablename__ = "working_orders"

    id = Column(Integer, primary_key=True, index=True)
    order_id = Column(String, unique=True, index=True)
    # market / event context (also used to build the Trade on fill)
    market_ticker = Column(String, index=True)
    event_slug = Column(String, nullable=True)
    bucket_label = Column(String, nullable=True)
    city_key = Column(String, nullable=True)
    metric = Column(String, nullable=True)
    target_date = Column(String, nullable=True)   # ISO date
    token_id = Column(String, nullable=True)      # the outcome token we post the BUY on
    condition_id = Column(String, nullable=True)  # for the Data API /trades fill feed
    direction = Column(String)                    # side we BUY: "yes" or "no"

    # order terms
    limit_price = Column(Float)
    size_shares = Column(Float)                    # requested shares
    intended_cash = Column(Float)                 # cash budget (shares * limit_price)
    tif = Column(String, default="GTD")
    created_ts = Column(Float)
    expiration_ts = Column(Float, nullable=True)

    # lifecycle / simulator state
    status = Column(String, default="OPEN", index=True)  # OPEN/PARTIALLY_FILLED/FILLED/EXPIRED/CANCELLED/REJECTED
    filled_shares = Column(Float, default=0.0)
    avg_fill_price = Column(Float, nullable=True)
    queue_ahead = Column(Float, default=0.0)
    last_poll_ts = Column(Float)

    # context for the Trade created on fill
    model_probability = Column(Float, nullable=True)
    market_price_at_entry = Column(Float, nullable=True)
    edge_at_entry = Column(Float, nullable=True)
    bias_corrected = Column(Boolean, nullable=True)
    signal_id = Column(Integer, nullable=True)
    trade_id = Column(Integer, nullable=True)     # the Trade row created when it filled
    created_at = Column(DateTime, default=datetime.utcnow)


def init_db():
    """Initialize database tables."""
    Base.metadata.create_all(bind=engine)
    ensure_schema()


def ensure_schema():
    """Ensure newer schema fields exist even if migration wasn't run."""
    inspector = inspect(engine)
    try:
        columns = [col["name"] for col in inspector.get_columns("trades")]
    except Exception:
        return

    if "event_slug" not in columns:
        stmt = "ALTER TABLE trades ADD COLUMN event_slug VARCHAR"
        if engine.dialect.name not in ("sqlite", "mysql"):
            stmt = "ALTER TABLE trades ADD COLUMN IF NOT EXISTS event_slug VARCHAR"

        with engine.connect() as conn:
            with conn.begin():
                conn.execute(text(stmt))

    if "market_type" not in columns:
        with engine.connect() as conn:
            with conn.begin():
                conn.execute(text("ALTER TABLE trades ADD COLUMN market_type VARCHAR DEFAULT 'btc'"))

    if "fee" not in columns:
        with engine.connect() as conn:
            with conn.begin():
                conn.execute(text("ALTER TABLE trades ADD COLUMN fee FLOAT DEFAULT 0.0"))

    if "bucket_label" not in columns:
        try:
            with engine.connect() as conn:
                with conn.begin():
                    conn.execute(text("ALTER TABLE trades ADD COLUMN bucket_label VARCHAR"))
        except Exception as e:
            logger.warning(f"Could not add trades.bucket_label: {e}")

    if "bias_corrected" not in columns:
        try:
            with engine.connect() as conn:
                with conn.begin():
                    conn.execute(text("ALTER TABLE trades ADD COLUMN bias_corrected BOOLEAN"))
        except Exception as e:
            logger.warning(f"Could not add trades.bias_corrected: {e}")

    # Add calibration columns to signals table
    try:
        signal_columns = [col["name"] for col in inspector.get_columns("signals")]
    except Exception:
        signal_columns = []

    if signal_columns:
        with engine.connect() as conn:
            for col, coltype in [
                ("actual_outcome", "TEXT"),
                ("outcome_correct", "BOOLEAN"),
                ("settlement_value", "FLOAT"),
                ("settled_at", "DATETIME"),
                ("market_type", "VARCHAR DEFAULT 'btc'"),
                ("net_edge", "FLOAT"),
                ("entry_price", "FLOAT"),
                ("cost", "FLOAT"),
                ("rel_spread", "FLOAT"),
                ("liquidity", "FLOAT"),
            ]:
                if col not in signal_columns:
                    try:
                        with conn.begin():
                            conn.execute(text(f"ALTER TABLE signals ADD COLUMN {col} {coltype}"))
                    except Exception as e:
                        # Don't fail startup, but don't hide it either — a real
                        # migration failure here silently breaks calibration.
                        logger.warning(f"Could not add signals.{col}: {e}")


def get_db():
    """Get database session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
